### ISSUE TITLE
"Error: unable to connect to reddit" misleading when reddit is down (Firefox)

### ISSUE THREAD

**Issue by BawdyInkSlinger** [reveddit/real-time-extension#10]
This morning, I received some notifications about 2 approved actions, then 2 removed actions. I clicked on the extension icon and it tried to load the webpage. After a few seconds, it showed me this error:

![image](https://user-images.githubusercontent.com/51732963/213296033-d16cc9d5-bcf2-4a9c-9819-010ecf5bcfde.png)

I followed the instructions and then refreshed (ctrl+shift+r), but it still returns this error. 

The reason it's unable to reach reddit is because of reddit outages. Perhaps in these cases, the pop-up description could say as much. Personally, I've never had to turn off tracking settings. Maybe that information is no longer true anyway.

[Here is a .har file](https://gist.github.com/BawdyInkSlinger/6a12d46eb4482fecb879dc375d0c3a77) capturing the relevant request/response from reddit in this scenario. You can view it by saving it as a file and uploading it here: https://toutpt.github.io/har-editor/

Also, the extension is informing me of two approved and then two removed the actions over and over again, which is kind of annoying, but given the rarity of reddit outages, I barely mind. Only bringing it up in case you feel otherwise.

**Comment by rhaksw** [comment]
> The reason it's unable to reach reddit is because of reddit outages. Perhaps in these cases, the pop-up description could say as much. Personally, I've never had to turn off tracking settings. Maybe that information is no longer true anyway.

Thanks, I updated the wording to clarify that the issue may or may not be the tracking protection setting. In most cases it is. See my comment [here](https://old.reddit.com/r/technology/comments/jp4j76/google_admits_to_censoring_the_world_socialist/gbfqdf2/?context=1),

> The source of this problem is a list of domains that a Firefox partner called disconnect.me decides are trackers. [Reddit is on that list](https://github.com/disconnectme/disconnect-tracking-protection/blob/b3f9cdcea541ab876e63970daadc490f9de2befa/services.json#L10851), so requests to reddit are blocked. The only way around it right now is to prompt users to disable the feature.
> 
> This [6 year old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1101005) documents sites broken by tracking protection. New sites are regularly added there.
> 
> I once [discussed](https://groups.google.com/forum/#!topic/mozilla.dev.privacy/XO84EzrwWp0) this with Firefox devs and couldn't find a better way to deal with it than to just prompt users explaining why the site does not load. A lot of users are happy to discover the problem, and I expect others simply use a different browser. IMO this feature drives people away from Firefox rather than towards it. YMMV

The tracking-protection-specific error message in your screenshot will come up if you have the setting "Send websites a “Do Not Track” signal that you don’t want to be tracked" set to "Always":

![do-not-track-setting](https://user-images.githubusercontent.com/42944822/213335864-dbb87811-95c9-41c4-a2f1-f27c871764d9.png)

**Comment by dnet890** [comment]
@rhaksw I already did that and it does not worked. What do you think?

**Comment by rhaksw** [comment]
addressed in [reveddit/reveddit#16](https://github.com/reveddit/reveddit/issues/16#issuecomment-1566447043)
