### ISSUE TITLE
The extension says my post is unapproved but I have contradictory evidence [NSFW links]

### ISSUE THREAD

**Issue by BawdyInkSlinger** [reveddit/real-time-extension#11]
Sorry for the weird title but, in this case,  I am confused about the true state of things. 

When I [visit this post](https://new.reddit.com/r/TrueMonsterGirls/comments/111hua3/comment/j8lqfyw/?context=3), the Firefox extension says this:

![image](https://user-images.githubusercontent.com/51732963/219298051-b6040ff9-206d-43ac-b315-d7e4459d38a6.png)

Visually, it seems to be referring to the whole post. But when I visit reveddit by clicking on [the link in that message](https://www.reveddit.com/v/TrueMonsterGirls/comments/111hua3/textbased_rpg_in_monster_girl_farmer_centaurs_are/), visually, it seems to be referring to the root comment, not the post.

If I login with a different user, I can see this post on the 2nd page of r/TrueMonsterGirls . I've always been under the impression that a post is not removed if that can be done. If I view that post's comments with this different user, *my reply* to the root comment seems to be removed, but neither the extension nor reveddit.com UI suggested to me that's what it was saying. (Of course, there is some subjectivity in that, but the picture above does use the word "post" when reddit seems to have only removed a comment.)

I'm not sure what's going on. Maybe it's a UX issue? Thanks.

**Comment by rhaksw** [comment]
This is a bug that started today. Please see [here](https://www.reddit.com/r/reveddit/comments/113iq9u/extension_known_issue_false_removal_notices_on/) for details. I'm locking this thread to focus discussion in one place. Thanks.
