### ISSUE TITLE
The Firefox extension informs me of old posts every few days

### ISSUE THREAD

**Issue by BawdyInkSlinger** [reveddit/real-time-extension#9]
Every few days, the Firefox extension informs me of the same two deleted comments/post I've already seen. For months, nothing I've commented/posted has been deleted, so the effect this has a "the boy who cried wolf" effect. 

According to the extension's history, my comment/post is approved and removed over and over again:

![image](https://user-images.githubusercontent.com/51732963/204111915-a9abc59e-7b1a-4d5d-8ea5-48089263132f.png)

Considering these posts are months old (despite what the history says) and from unrelated subreddits, it seems unlikely. I am using 0.0.2.0 on Firefox 107.0 on Windows 10. Here are my options. Let me know if I can provide any other information to help:

![image](https://user-images.githubusercontent.com/51732963/204111984-a0c2fbd6-d0ac-49e3-9eca-e263a47dd4e7.png)

**Comment by rhaksw** [comment]
Interesting. I've never experienced this, and so far I'm unable to replicate it using your username. There was one similar report in a survey (it comes up when you uninstall the extension) which wrote,

> It only notified once. It keeps re-notifying me about the same removal over and over and over agian.

That user, like you, had a lot of history in NSFW subreddits. I don't know if that is throwing off something in the extension or with Reddit.

**Comment by rhaksw** [comment]
Hi, I issued a fix for this with version 0.0.2.1 of the extension. For details see [this comment](https://www.reddit.com/r/reveddit/comments/zc7tcm/reveddit_sending_repetitive_notifications/j40izto/).

**Comment by BlueGoliath** [comment]
Hi,

Has this fix been rolled out? Currently on Vivaldi and am getting notifications about mod actions despite same actions being set to 2.

Thanks.

**Comment by rhaksw** [comment]
Hi @BlueGoliath, assuming you have version 0.0.2.1 and are getting the erroneous _repeat_ notifications, please share a screenshot of your history page so I can verify. It's possible that the notification was correct.

If you think the notification was incorrect, you can try increasing the option "same-status count before alert" to 3 or 4.
